-- MySQL Script generated by MySQL Workbench
-- Tue Dec 15 04:14:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema course
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema course
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `course` DEFAULT CHARACTER SET utf8 ;
USE `course` ;

-- -----------------------------------------------------
-- Table `course`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `course`.`token` (
  `token_id` INT NOT NULL AUTO_INCREMENT,
  `token_uuid` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`token_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `course`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `course`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(128) NOT NULL,
  `user_role` ENUM("ADMIN", "USER") NOT NULL,
  `user_status` ENUM("BLOCKED", "ENABLE") NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_surname` VARCHAR(45) NOT NULL,
  `user_patronymic` VARCHAR(45) NOT NULL,
  `user_token_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_users_token1_idx` (`user_token_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_token1`
    FOREIGN KEY (`user_token_id`)
    REFERENCES `course`.`token` (`token_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `course`.`converter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `course`.`converter` (
  `converter_id` INT NOT NULL AUTO_INCREMENT,
  `byn` DOUBLE NOT NULL,
  `usd` DOUBLE NOT NULL,
  `eur` DOUBLE NOT NULL,
  `rub` DOUBLE NOT NULL,
  `converter_creation_date` BIGINT(255) NOT NULL,
  PRIMARY KEY (`converter_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `course`.`credit_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `course`.`credit_card` (
  `credit_card_id` INT NOT NULL AUTO_INCREMENT,
  `credit_card_number` BIGINT(255) NOT NULL,
  `credit_card_service_end` BIGINT(255) NOT NULL,
  `credit_card_cvv` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`credit_card_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `course`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `course`.`account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `account_creation_date` BIGINT(255) NOT NULL,
  `account_money_amount` DOUBLE NOT NULL,
  `account_status` ENUM("NOT_CONFIRMED", "ENABLE", "BLOCKED", "CLOSED") NOT NULL,
  `account_user_id` INT NOT NULL,
  `account_token_id` INT NOT NULL,
  `account_credit_card_id` INT NOT NULL,
  PRIMARY KEY (`account_id`),
  INDEX `fk_account_users1_idx` (`account_user_id` ASC) VISIBLE,
  INDEX `fk_account_token1_idx` (`account_token_id` ASC) VISIBLE,
  INDEX `fk_account_credit_card1_idx` (`account_credit_card_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_users1`
    FOREIGN KEY (`account_user_id`)
    REFERENCES `course`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_token1`
    FOREIGN KEY (`account_token_id`)
    REFERENCES `course`.`token` (`token_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_account_credit_card1`
    FOREIGN KEY (`account_credit_card_id`)
    REFERENCES `course`.`credit_card` (`credit_card_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `course`.`transaction_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `course`.`transaction_history` (
  `transaction_history_id` INT NOT NULL AUTO_INCREMENT,
  `from_account_id` INT NOT NULL,
  `to_account_id` INT NOT NULL,
  `transaction_history_money_amount` DOUBLE NOT NULL,
  `transaction_date` BIGINT(255) NOT NULL,
  PRIMARY KEY (`transaction_history_id`),
  INDEX `fk_transaction_history_account1_idx` (`from_account_id` ASC) VISIBLE,
  INDEX `fk_transaction_history_account2_idx` (`to_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_history_account1`
    FOREIGN KEY (`from_account_id`)
    REFERENCES `course`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_history_account2`
    FOREIGN KEY (`to_account_id`)
    REFERENCES `course`.`account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
